language: csharp
solution: H3Control.sln 
install:
  - sudo apt-get install -y sysbench ffmpeg redis-server memcached
  - nuget restore H3Control.sln 
script:
  - uname -a
  - cat /etc/*release
  - mono --version
  - java -version
  - #du -h -d 4
  - xbuild H3Control.sln /t:Rebuild /p:Configuration=Release /verbosity:normal
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - sysbench --test=cpu --cpu-max-prime=20000 --max-time=1  --num-threads=1 run > /dev/null
  - sysbench --test=cpu --cpu-max-prime=20000 --max-time=20 --num-threads=1 run 
  
  